language: go

install:
  - go get -d -t
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --enable-all .
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
