language: go
matrix:
  allow_failures:
    - go: master
  fast_finish: true
env:
- GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
- stage: test
script:
  - golint -set_exit_status
  - go tool vet .
  - go test -v -race ./...
