language: go
go:
- master

matrix:
  allow_failures:
    - go: master
fast_finish: true


jobs:
  include:
    - stage: test
      script: 
      - go test
      - go tool vet .
    - stage: style
      script:
      - diff -u <(echo -n) <(gofmt -d -s .)
      
    
